### PR TITLE
Add external images support

### PR DESCRIPTION
**Pull request by bleleve**
Hello,

This pull request add the support of external images.

When the flag is set to "Yes", images will not be downloaded and URLs will be inserted as they are :

``` php
$import = Mage::getModel('fastsimpleimport/import');

$import->setDownloadExternalImages(false)
       ->processProductImport($data);
```

``` php
array(
    array(
        'sku' => 'TESTSKU',
        '_media_image' => 'http://www.example.com/img_01.jpg',
        '_media_lable' => 'Base Image Label',
        '_media_position' => 1,
        'image' => 'http://www.example.com/img_01.jpg',
        'small_image' => 'http://www.example.com/img_02.jpg',
        'thumbnail' => 'http://www.example.com/img_03.jpg'
    ),
    array(
        'sku' => null,
        '_media_image' => 'http://www.example.com/img_02.jpg',
        '_media_lable' => 'Small Image Label',
        '_media_is_disabled' => 1
    ),
    array(
        'sku' => null,
        '_media_image' => 'http://www.example.com/img_03.jpg',
        '_media_lable' => 'Thumbnail Label',
        '_media_is_disabled' => 1
    )
)
```

This doesn't add external images support into Magento, a custom extension is needed.

Best regards,
Benoît LELEVÉ
www.exsellium.com

### CODE REVIEW

**Comment by avstudnitz** [comment]
Well, we had external  image download support before. What does your solution do better than the old solution?
I agree, we have to document that.

**Comment by bleleve** [comment]
Hi,

As explained in my previous comment, when the flag is set to "Yes", images are not downloaded into Magento, their URLs are inserted as they are (this is useful for CDN hosted images).

A custom extension is needed in Magento in order to support these remote images.

Best regards.

**Comment by bleleve** [comment]
This should be renamed in setDownloadExternalImages (YES/no).

**Comment by avstudnitz** [comment]
Closed as we already have the feature to download product images.

**Comment by bleleve** [comment]
Hi,

It is not the same feature. With this PR images will NOT be downloaded. If you look into the gallery table after the import you will only see HTTP URLs.

Best regards.
Benoît.

**Pull request closed without merging**
