### PR TITLE
Fixes possible security issues with excel formula injection in csv data, see APPSEC-1110 (SUPEE-7405).

### PR DESCRIPTION
**Pull request by hostep**
See https://github.com/avstudnitz/AvS_FastSimpleImport/issues/277

Unescapes the csv data everywhere I could find a call to $source->current(). This was recently introduced in security patch SUPEE-7405:
https://github.com/brentwpeterson/magento-patches/blob/master/CE1.9-EE1.14/PATCH_SUPEE-7405_CE_1.9.2.2_v1-2016-01-20-04-35-33.sh#L1697

Also replaced all `$this->getSource()` calls to `this->_getSource()`, so it is consistent all over the codebase (the only difference between those two methods is the public vs protected visibility & the message in the exception).

Also always use a `$source` variable, instead of multiple `this->_getSource()` calls in the same method.

Note: I have **not** tested this. So please review & test before merging!

### CODE REVIEW

**Comment by diglin** [comment]
quick question, is unEscapeCSVData helper method only available on Magento 1.9.2.3 ? If yes, forget your pull request, it needs retro compatibility otherwise it breaks the use on other projects

**Comment by hostep** [comment]
The method is available once you install [security patch SUPEE-7405](https://magento.com/security/patches/supee-7405) which everybody should do or should already have done. I just checked most of the patch files and the lowest version which gets this method is Magento CE 1.5.0.0. Since AvS_FastSimpleImport claims to be compatible with Magento CE 1.6.0.0 and higher this should be no issue.
I also trust the users of AvS_FastSimpleImport to be aware of these security patches.

**Comment by avstudnitz** [comment]
Thank you!

**Comment by hostep** [comment]
Thank for merging Andreas! :)

**Pull request merged**
