### PR TITLE
#258 fix positioning of super attributes in configurable products.

### LINKED ISSUE #258: _super_attribute_codes positioning wrong in backend
Hey,

as seen in this image
image

The configurable product has two configurable options "sw_size" and "sw_packing_unit" and the "sw_packing_unit" should be on the last position as configurable attribute.

However in the backend, it looks like this:

image

As seen in this image, the "Packing Unit" attribute (= sw_packing_unit) is on the first positon as a configurable attribute, which we dont want.

Is this a bug ? Does the positioning inside the "_super_attribute_codes" array even matter?

FastSimpleImport Version: "b5beca53d40133671548f827e4c4e9f4571cda08"
Magento Version: 1.9.2.1

Thanks!

### PR DESCRIPTION
**Pull request by pquerner**
Fixes #258 

Please do test!
@avstudnitz

### CODE REVIEW

**Comment by riker09** [comment]
Quick test in development yielded no error and the desired results. Looking good!

**Comment by paales** [comment]
Except for a comment nitpick – should be `//` for oneline comments – everything looks fine.

**Comment by avstudnitz** [comment]
Okay, I'll merge it then :-) Thanks @pquerner for development and @riker09 for testing!

**Comment by riker09** [comment]
@avstudnitz 
t8upv ;)

**Pull request merged**
