### PR TITLE
Added ability to import downloadable products with downloadable links

### PR DESCRIPTION
**Pull request by Maksold**

### CODE REVIEW

**Comment by Maksold** [comment]
Here is sample code for importing downloadable product with downloadable link:

`
<?php
require 'app/Mage.php';
Mage::app();

$data = array(
    array(
        'sku' => '1234759567',
        '_type' => 'downloadable',
        '_attribute_set' => 'Default',
        '_product_websites' => 'base',
        'name' => 'Downloadable Product',
        'price' => 0.99,
        'description' => 'Default',
        'short_description' => 'Default',
        'weight' => 0,
        'status' => 1,
        'visibility' => 4,
        'tax_class_id' => 2,
        'qty' => 76,
        'downloadable_links_file' => 'https://upload.wikimedia.org/wikipedia/commons/c/c4/PM5544_with_non-PAL_signals.png',
        'downloadable_links_title' => 'PM5544_with_non-PAL_signals.png',
        'downloadable_links_nod' => '100',
    ),
    // add more products here
);

/** @var $import AvS_FastSimpleImport_Model_Import */
$import = Mage::getModel('fastsimpleimport/import');
try {
    $import->processProductImport($data);
} catch (Exception $e) {
    print_r($import->getErrorMessages());
}
`

**Comment by Maksold** [comment]
@avstudnitz, @paales could you please approve this pull request?

**Comment by avstudnitz** [comment]
@Maksold @EliasKotlyar Thank you both!
When I try to import with the given example script, I am getting the following error:

```
Array
(
    [Required attribute 'links_purchased_separately' has an empty value] => Array
        (
            [0] => 1
        )

)
````

**Comment by Maksold** [comment]
It's because if forgot to add requred 'links_purchased_separately' attribute. Here is working code:

```
<?php
require 'app/Mage.php';
Mage::app();

$data = array(
    array(
        'sku' => '1234759567',
        '_type' => 'downloadable',
        '_attribute_set' => 'Default',
        '_product_websites' => 'base',
        'name' => 'Downloadable Product',
        'price' => 0.99,
        'description' => 'Default',
        'short_description' => 'Default',
        'weight' => 0,
        'status' => 1,
        'visibility' => 4,
        'tax_class_id' => 2,
        'qty' => 76,
        'downloadable_links_file' => 'https://upload.wikimedia.org/wikipedia/commons/c/c4/PM5544_with_non-PAL_signals.png',
        'downloadable_links_title' => 'PM5544_with_non-PAL_signals.png',
        'downloadable_links_nod' => '100',
        'links_purchased_separately' => '1'
    ),
    // add more products here
);

/** @var $import AvS_FastSimpleImport_Model_Import */
$import = Mage::getModel('fastsimpleimport/import');
try {
    $import->processProductImport($data);
} catch (Exception $e) {
    print_r($import->getErrorMessages());
}
```

@avstudnitz Can you please merge this pull request?

**Comment by norgeindian** [comment]
Just tested your improvement. Works fine so far, thanks a lot!

There are just three things which should be improved in my opinion:

1. We did not have the folder `downloadable/files/links` in our media directory. In this case, the download files are not created and so no download file is uploaded.
So it should first be guaranteed, that this folder exists or it should be created if not.
2. As Magento saves such files in multiple sub-folders (your example URL for example is stored in `downloadable/files/links/p/m`, when you upload it manually in the Magento backend), it would also be great, if we do it the same way.
3. Another issue I found is the download link.
Right now all download links are imported as files.
It would be perfect to have the option to import them as URL, too.
Therefore, two new array keys would be good: One for the URL (`downloadable_links_url`) and one for the type (`downloadable_links_type`).

@avstudnitz @nhp Could you please merge this pull request?
@Maksold  Do you want to work on my ideas or should I implement it by myself as soon as it is merged and provide another PR?

**Pull request merged**
