### PR TITLE
case-insensitive comparison of dropdown/mutliselect attribute options

### LINKED ISSUE #233: Problems with same option in capital or normal letters not case sensitive
Andreas,

I'm happy to use your extension. Our customer has a large old database cleaning up right now. So in the first import we had a multiselect attribute "TRACTOR" now they changed to "Tractor". So now 2 similar options exist and it looks like while importing the result is just random which option is taken. As I found in the Function "prepareAttributesForSave" you use strtolower for the option and in the array _attributes all options are already converted with strtolower and there is only 1 option "tractor" instead of 2.

Is there a reason why setting values with options it's not possible to do that case sensitive? I didn't find right away where and how the options are loaded and perhaps converted?

You can also answer in german if you want to. Thanks in advance

Christoph

### PR DESCRIPTION
**Pull request by sprankhub**
fixes #233

### CODE REVIEW

**Comment by paales** [comment]
@sprankhub Might it be a good Idea to use `mb_strtolower` instead of `strtolower`?

**Comment by sprankhub** [comment]
@paales In theory, yes. Practically, mbstring is a non-standard PHP extension... Should we check if `mb_strtolower` is available and if yes, use it instead of a normal `strtolower`?

**Comment by avstudnitz** [comment]
See also #271 regarding the strtolower / mb_strtolower question.
We could put a function into the helper which uses `mb_strtolower` or `strtolower` depending on a check for availability of `mb_strtolower`.

**Comment by paales** [comment]
Isn't solving issues that don't occur? I mean, who hasn't installed the [Multi Byte](http://php.net/manual/en/book.mbstring.php) extension?

**Comment by sprankhub** [comment]
Since it is not a default extension and not required by Magento, you should not require it. I currently update this PR with a `mb_strtolower` alternative if available.

**Comment by sprankhub** [comment]
So I just implemented and added a multibyte switch. Once this is merged, I am happy to replace all occurrences of `strtolower` with my new helper method and open a new pull request (if you like & merge).

**Comment by sprankhub** [comment]
Any other unclear stuff? ;-)

**Comment by jamescowie** [comment]
Code looks good and no errors detected thanks buddy

**Pull request merged**
