### PR TITLE
Fixes multibyte character compare on select/multiselect validation

### PR DESCRIPTION
**Pull request by tinchodev**
Fixes multibyte character issue on select/multiselect product attributes

### CODE REVIEW

**Comment by avstudnitz** [comment]
We have 18 occurences of `strtolower`. Should they all be replaced by `mb_strtolower`?

**Comment by tinchodev** [comment]
It is always nice to support multibyte characters either for compare or display .
For this particular case, option labels like "NIÑO" were lower-cased to "niÑo" since strtolower cannot handle multibyte characters, hence the validation failed. Nevertheless the change will add **mbstring** PHP extension as requirement to use the module, which usually is enabled, but it is not a default PHP extension, that will be the only catch.

**Comment by avstudnitz** [comment]
@tinchodev Thanks for clarification. IMO add the mbstring extension as requirement is no big problem. Am I right that we should replace all occurences of `strtolower` with `mb_strtolower` then, or are there any additional drawbacks?

**Comment by tinchodev** [comment]
Both functions work the same way, technically there are no additional drawbacks.

**Comment by avstudnitz** [comment]
Fixed that in 0a50cc4 for all occurences of strtolower

**Comment by StevenSch** [comment]
With this this fix im getting the followig error :
**Notice: Undefined index: gelöschte artikel in C:\xampp\htdocs\devserver\app\code\community\AvS\FastSimpleImport\Model\Import\Entity\Product\Type\Simple.php on line 33**

**Comment by avstudnitz** [comment]
@StevenSch Can you show me the import data you are using where "gelöschte Artikel" occurs?

**Comment by StevenSch** [comment]
We planning up a complex multishop-system with more than one root-category (one for each shop).
Dataexchange should be realised with fastsimpleimport and ho_import.
This is a very short snippet from our csv-import-file.
[shortlist.txt](https://github.com/avstudnitz/AvS_FastSimpleImport/files/760075/shortlist.txt)

**Comment by tinchodev** [comment]
@StevenSch 'gelöschte Artikel' is not being lowercased, please confirm do you have the mb_string extension enabled on your php.ini

**Comment by tinchodev** [comment]
@StevenSch "gelöschte Artikel" is not being lowercased for some reason on your setup, I could not reproduce locally but I'm not running Windows which I suspect may be somehow related to the described issue.
Please run a standalone test and share the output :

`echo mb_strtolower("gelöschte Artikel", mb_detect_encoding("gelöschte Artikel"));`

then 

`echo strtolower("gelöschte Artikel");`

**Comment by StevenSch** [comment]
<?php
/** File test.php / Encoding UTF8  */
echo mb_strtolower("gelöschte Artikel", mb_detect_encoding("gelöschte Artikel")); 
echo "\n";
echo strtolower("gelöschte Artikel");
?>

local environment (windows)
php test.php results:
gel├Âschte artikel
gelÒÂschte artikel

This seems to be a windows problem, because on our dev-server (Linux):
php_cli test.php results:
gelöschte artikel
gelöschte artikel

**Comment by sprankhub** [comment]
The `strtolower` vs. `mb_strtolower` issue should be fixed everywhere now.

Windows is not supported by Magento, so we do not support it either.

**Pull request closed without merging**
