### PR TITLE
uses strtolower from helper (mb_stringtower fallback)

### PR DESCRIPTION
**Pull request by riconeitzel**

### CODE REVIEW

**Comment by riconeitzel** [comment]
@nhp it uses "strtolower" in vanilla magento … but it needs to use mb_strtolower … so core hacking was no option for me #benmarksknowseverything

**Comment by sprankhub** [comment]
I just stumbled upon the same issue and can confirm that this PR fixes it. Please merge @nhp :)

**Comment by riconeitzel** [comment]
yo man - pull that request where it belons #unitedStyle 😂 #scnr

**Comment by sprankhub** [comment]
This is already fixed in the latest develop branch.

**Pull request closed without merging**
