### PR TITLE
Add downloadable urls

### PR DESCRIPTION
**Pull request by pixelhed**
I had the need for this in a project and thought it might be useful for someone else.

### CODE REVIEW

**Review by avstudnitz — APPROVED** [review]

**Comment by avstudnitz** [comment]
Thank you!

**Comment by sprankhub** [comment]
This breaks https://github.com/avstudnitz/AvS_FastSimpleImport/pull/393 :-/ We probably do quite similar things. Unfortunately, I currently do not have the time / project, so that I can check in detail. Anyway, I still wanted to cross-link our PRs.

**Comment by avstudnitz** [comment]
Ah, sorry about that, didn't have #393 in mind...

**Comment by pixelhed** [comment]
> This breaks #393 :-/ We probably do quite similar things. Unfortunately, I currently do not have the time / project, so that I can check in detail. Anyway, I still wanted to cross-link our PRs.

@sprankhub If you like i can look at integrating #393

**Comment by sprankhub** [comment]
This would be awesome @pixelhed :)

**Pull request merged**
