### PR TITLE
Fix nestedArrayAdapter bug with multiselect values at store-scoped data ...

### PR DESCRIPTION
**Pull request by kira-backes**
...lines.

All values but the first were lost (well, they were moved into the default scope) since the newly created data lines were not properly associated with the store scope. My solution is to just keep the _store column.

### CODE REVIEW

**Comment by kira-backes** [comment]
Additionally fixed a very specific bug:
Attribute was NULL in default row but had a value in store specific row. Now the entry was deleted from DB for the default row, which causes product collections in Magento to not load the store specific values (an SQL join which fails if the default entry is not there).

**Comment by kira-backes** [comment]
If you need separate branches and two pull requests please tell me

**Comment by kira-backes** [comment]
@avstudnitz Or do you need them for develop branch?

**Comment by avstudnitz** [comment]
@kira-backes Doesn't matter much - develop would be better, but you don't need to switch that now, I can do that on the command line.
Sorry for the delay, I'll try to check it in the next few days. Thanks for your contribution!

**Comment by avstudnitz** [comment]
Merged into develop branch. Thanks a lot!

**Pull request closed without merging**
